### ISSUE TITLE
There is no package called 'packrat'

### ISSUE THREAD

**Issue by scworland-usgs** [rstudio/cloudml#168] opened 2018-06-09 02:02 UTC
I am receiving the following error in the log:

```
Error in loadNamespace(name) : there is no package called 'packrat'
```

This occurs with something as simple as this `flags_test.R` file (I stole this example from issue #107),

```r
library(keras)

FLAGS <- flags(
  flag_integer("test_flag", 123)
)

message("Flag:", FLAGS$test_flag)
```

```r
cloudml::cloudml_train("flags_test.R", flags = list(test_flag = 456))
```

I also tried it with this example from issue #130 and received the same error,

```r
dir.create("mnist-train")
file.copy(system.file("examples/mnist/train.R", package = "cloudml"), "mnist-train")
setwd("mnist-train")
cloudml::cloudml_train()
```
```
master-replica-0 Package: yaml  master-replica-0
master-replica-0 Source: CRAN  master-replica-0
master-replica-0 Version: 2.1.19  master-replica-0
master-replica-0 Hash: 6e3d988c25e34c31f668e0ae41dc3259  master-replica-0
master-replica-0 Error in loadNamespace(name) : there is no package called 'packrat'  master-replica-0
master-replica-0 Calls: retrieve_packrat_packages ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>  master-replica-0
master-replica-0 Execution halted  master-replica-0
master-replica-0 Command ['Rscript', '/root/.local/lib/python2.7/site-packages/cloudml-model/cloudml/deploy.R'] failed: exit code 1  master-replica-0
The replica master 0 exited with a non-zero status of 1. 
Job failed. 
```
 
![image](https://user-images.githubusercontent.com/11577981/41191303-7714a2a2-6bbb-11e8-92cc-0ee3197da87d.png)

I have also tried it with an explicit `library()` call for packrat. 

`sessioninfo::session_info()`

```
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 os       macOS Sierra 10.12.2        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-06-09                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       source                          
 assertthat    0.2.0   2017-04-11 CRAN (R 3.4.0)                  
 backports     1.1.2   2017-12-13 cran (@1.1.2)                   
 base64enc     0.1-3   2015-07-28 CRAN (R 3.4.0)                  
 clisymbols    1.2.0   2017-05-21 CRAN (R 3.4.0)                  
 cloudml       0.5.0   2018-06-08 Github (rstudio/cloudml@729aa3e)
 crayon        1.3.4   2017-09-16 CRAN (R 3.4.1)                  
 debugme       1.0.2   2017-03-01 CRAN (R 3.4.0)                  
 jsonlite      1.5     2017-06-01 cran (@1.5)                     
 keras       * 2.1.6   2018-04-29 CRAN (R 3.4.4)                  
 lattice       0.20-35 2017-03-25 CRAN (R 3.4.0)                  
 magrittr      1.5     2014-11-22 CRAN (R 3.4.0)                  
 Matrix        1.2-10  2017-04-28 CRAN (R 3.4.0)                  
 packrat       0.4.9-3 2018-06-01 CRAN (R 3.4.4)                  
 processx      3.1.0   2018-05-15 cran (@3.1.0)                   
 R6            2.2.2   2017-06-17 CRAN (R 3.4.0)                  
 Rcpp          0.12.16 2018-03-13 cran (@0.12.16)                 
 reticulate    1.7     2018-04-28 CRAN (R 3.4.4)                  
 rprojroot     1.3-2   2018-01-03 cran (@1.3-2)                   
 rstudioapi    0.7     2017-09-07 cran (@0.7)                     
 sessioninfo   1.0.0   2017-06-21 CRAN (R 3.4.1)                  
 tensorflow    1.5     2018-01-17 CRAN (R 3.4.3)                  
 tfruns        1.3     2018-02-18 CRAN (R 3.4.3)                  
 whisker       0.3-2   2013-04-28 CRAN (R 3.4.0)                  
 withr         2.1.2   2018-06-08 Github (jimhester/withr@dbcd7cd)
 yaml          2.1.19  2018-05-01 cran (@2.1.19)                  
 zeallot       0.0.6   2017-09-28 cran (@0.0.6)
```

**Comment by zamorarr** [comment] 2018-06-11 12:51
I am also seeing this error when trying to train the simple mist example as pointed out above.

**Comment by javierluraschi** [comment] 2018-06-11 20:05
I can reproduce a slightly different version of this error:

```
Error in loadNamespace(name) : there is no package called 'jsonlite'
```

investigating...

**Comment by javierluraschi** [comment] 2018-06-12 10:34
Fixed with https://github.com/rstudio/cloudml/commit/b0f3322fede921d083edbff52adc2cb4e612532a, will push a CRAN update later today.

**Comment by javierluraschi** [comment] 2018-06-12 10:35
Please open new issue if this problem persists after installing with:

```r
devtools::install_github("rstudio/cloudml")
```

**Closed by javierluraschi** 2018-06-12 10:34 UTC

**Comment by zamorarr** [comment] 2018-06-13 01:28
Works for me now! Very fun. Thank you.
