### ISSUE TITLE
should we allow users to override gcloud / flags configuration within 'train_cloudml()'?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/cloudml#16] opened 2017-09-27 20:51 UTC
Currently, users specify arguments for their own application in `flags.yml`, and options associated with `gcloud` / `cloudml` configuration in `gcloud.yml`.

Do we want to make it possible for users to set these dynamically (ie, in R code) as well? If so, how should we support it? Or, should we require that any of these kinds of changes be reflected in `flags.yml` / `gcloud.yml`? Alternatively, should we allow users to select different configuration files to be used during deployment?

For context, I'm imagining someone who might want to kick off a training run with something like:

```R
cloudml::train_cloudml(
    application = getwd(),
    config = "cloudml",
    flags = list(num_epochs = 1.0),
    gcloud = list(runtime.version = "1.3")
)
```

We currently allow something like this with the 'overlay' (we accept things passed through `...` and use them as appropriate); it's possible that we might want to take this out if we feel it doesn't play nicely with flags.

**Comment by jjallaire** [comment] 2017-09-28 01:27
Yes, the `flags` parameter in particular is trivially supported by just forwarding it's value to `training_run` (which also supports a `flags` parameter in just this fashion). 

In terms of `gcloud` I hadn't thought about it but it does seem like some might have use for this (although it would certainly be defensible to just start with the config file and add a `gcloud` parameter as needed/requested.

**Comment by kevinushey** [comment] 2017-09-28 02:16
Sounds good. FWIW there is a bit of extra work to be done on the deployment side -- since the flags will be defined on the user's computer but need to be applied and set on the deployment machine, we'd have to serialize those flags, transfer them as part of the bundle, then re-read and use them in the ensuing call to `training_run()`. (All the infrastructure for this is thankfully in place already; just wanted to double check that this was in line with the `tfruns` philosophy)

**Comment by jjallaire** [comment] 2017-09-28 09:28
Yes, all of that makes complete sense.

**Comment by jjallaire** [comment] 2017-12-11 19:33
We decided we will have 3 arguments like this:

```r
flags = "flags.yml"
cloudml = "cloudmy.yml"
gcloud = "gcloud.yml"
```

Then users can pass lists as an alternative to any of those file values.

**Comment by jjallaire** [comment] 2017-12-11 19:37
The gcloud config file will support forwarding all gcloud wide config flags

**Comment by jjallaire** [comment] 2017-12-11 19:48
Duplicate of #5

**Closed by jjallaire** 2017-12-11 19:48 UTC
