### ISSUE TITLE
where should auxiliary configuration be specified?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/cloudml#17] opened 2017-09-28 20:55 UTC
There are a few configuration items that need a home:

- [ ] `exclude` / `include`: Controlling what files do, or don't, enter the bundle for deployment;
- [ ] `packrat`: Whether `packrat` should be used to handle deployment.

I'm sure other things will pop up as we consider new deployment scenarios.

@jjallaire, any thoughts on where these should live?

- `flags.yml`, as part of some separate `deployment` config key?
- `config.yml`, as a totally separate configuration?
- Something else?

**Comment by terrytangyuan** [comment] 2017-09-28 21:34
Maybe also expose the paths to those config files so users can specify those themselves for situations where these yaml files are generated dynamically?

**Comment by jjallaire** [comment] 2017-09-28 22:15
I wonder if we shouldn't move to having a `cloudml.yml` file that includes:

- gcloud config
- exclude / include / packrat / etc.
- flags

It would of course be awesome if we could get the flags in there as well. Maybe something like this:

```yaml
gcloud:
   account: foo
   project: bar
include: *.R
exclude: *.mp3
packrat: true
flags:
    learning_rate: 0.001
    train_data: gs://example.com/data.csv
```

I think that's the most simple and coherent expression for the user. One question is how we marry this with the notion of the user needing to only do this in their R script:

```r
FLAGS <- flags(
    flag_numeric("learning_rate", 0.005),
    flag_string("train_data", "data.csv")
)
```

Perhaps we could enhance the `flags()` function to not only look for this:

```
flags.yml
   <config-name>:
         flag: value
```

But also this:

```
<config-name>.yml
   flags:
        flag: value
```

That way it would work fine for local oriented configurations which would just use `flags.yml` but could also adapt to the end-to-end cloudml scenario without proliferation of config files.

I could be oversimplifying, but I'm definitely trying to go for as simple as possible an expression for the user. 

In any case I think we should discuss this realtime before making any decisions.

**Comment by kevinushey** [comment] 2017-10-03 19:08
Just looping back on this, I think we've decided on the following structure:

| File | Purpose |
|-|-|
| `flags.yml` | Application-specific configuration flags. |
| `cloudml.yml` | Configuration for e.g. `gcloud` [`project`, `account`] and `cloudml`-specific deployment settings [`packrat`] |

This implies that `flags.yml` is agnostic to the deployment mechanism used; a separate configuration file is used to manage deployment-related configuration.

**Comment by jjallaire** [comment] 2017-10-03 20:10
I think this is a good place to have landed.

**Comment by terrytangyuan** [comment] 2017-10-03 21:21
I am trying to understand better and put pieces together. Is there any good reference for me catch up with CloudML and our approach?

**Comment by kevinushey** [comment] 2017-10-03 22:20
This is probably the best reference for Cloud ML itself:

https://cloud.google.com/ml-engine/docs/concepts/technical-overview

The short version of what we're trying to accomplish is batch-wise training + prediction of TensorFlow applications using Google's ML Engine. We're trying to accomplish this in the following way:

1. Use the `gcloud` command line tool for the submission of training + prediction 'jobs',
2. Defining some 'best practices' and documenting how an application can be configured for deployment,
3. Use `tfruns::training_run()` on the Google Cloud side to handle runs, and synchronize run outputs for easy viewing and introspection using other tooling in the `tfruns` package.

In the end, we're hoping that submitting a job to ML Engine is as simple as something like:

```
job <- cloudml_train(...)      # submits job to ML Engine
collected <- job_collect(job)  # waits for job to complete
```

And hopefully, once we've figured out the right workflow, we'll augment it with existing RStudio tools (e.g. run a job in a Terminal pane so you can see streamed log output as it comes in).

Because ML Engine expects a Python package as a trainable artefact, we're basically hooking into that framework by disguising an R application as a Python package, uploading that Python package, and then choosing an R endpoint as the mechanism through which the model is trained / predicted on.

**Comment by terrytangyuan** [comment] 2017-10-04 08:26
Thanks Kevin! I'll read through it soon.

**Comment by jjallaire** [comment] 2017-12-11 19:30
Duplicate of #56

**Closed by jjallaire** 2017-12-11 19:30 UTC
