### ISSUE TITLE
separate 'cloudml.yml', 'flags.yml'

### ISSUE THREAD

**Issue by kevinushey** [rstudio/cloudml#11] opened 2017-09-11 20:15 UTC
We need some way of automatically detecting + setting the active project + account for deployments.

For command-line deployments, this implies constructing a command line string of the form:

    gcloud --project <project> --account <account> ml-engine <...>

I'm guessing this should be encoded as part of `config.yml`?

**Comment by kevinushey** [comment] 2017-09-11 20:18
From the `gcloud --help` documentation:

```
GCLOUD WIDE FLAGS

     --account=ACCOUNT
        Google Cloud Platform user account to use for invocation. Overrides the
        default core/account property value for this command invocation.

     --configuration=CONFIGURATION
        The configuration to use for this command invocation. For more
        information on how to use configurations, run: gcloud topic
        configurations. You can also use the [CLOUDSDK_ACTIVE_CONFIG_NAME]
        environment variable to set the equivalent of this flag for a terminal
        session.

     <...>

     --project=PROJECT_ID
        The Google Cloud Platform project name to use for this invocation. If
        omitted then the current project is assumed. Overrides the default
        core/project property value for this command invocation.
```

We might also want to build on top of the configuration file mechanism already supported by the SDK here.

**Comment by kevinushey** [comment] 2017-09-11 20:52
We should also provide some helpers for installing the Google Cloud SDK.

**Comment by kevinushey** [comment] 2017-09-11 22:20
As per conversation with @jjallaire, we're going to move the cloudml-specific stuff to a separate configuration file, `cloudml.yml` (or `gcloud.yml`). In here is where users would specify these sorts of flags.

**Comment by kevinushey** [comment] 2017-09-14 18:50
@jjallaire we should chat a bit about the `gcloud.yml` file for `gcloud`-specific configuration. Note that `gcloud` has its own configuration mechanism, as described in https://cloud.google.com/sdk/gcloud/reference/config/set.

Should we instead just target users as to how they can create project-specific configurations using tools already available in the SDK (implies no `gcloud.yml`), or should we instead have our own treatment (using `gcloud.yml`)?

Alternatively, we could have `gcloud.yml` but automatically search for + use a configuration file if available; e.g. suppose we had a `gcloud.yml` file containing only the contents:

```
configuration: "kevinushey"
```

then we could search + use the associated configuration called `kevinushey`.

FWIW the command-line way of managing configurations is something like this:

```
gcloud config configurations create <config>
gcloud config configurations activate <config>
gcloud config set account "foo"
gcloud config set project "bar"
```

Note that this sequence of actions globally activates the configuration `<config>`, which seems somewhat undesirable (it's nice to just scope the configuration to ensuing `gcloud` commands we want to execute)

It seems to me like we might want to support both workflows, but advertise our own version based on `gcloud.yml` as it seems somewhat simpler and it's nice to have this configuration live as part of the project.

**Comment by jjallaire** [comment] 2017-12-11 19:49
duplicate of #56

**Closed by jjallaire** 2017-12-11 19:49 UTC
